name: Helm Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          charts-folder: "charts"
          deploy-branch: "gh-pages"
